Repository CS2113-AY1819S2-T09-2/main, pull requests merged in 2019-03, with the labels that each got.

#38 Add EditCommand and EditCommandPaser class
  .classpath
  .project
  docs/images/BrittonAlone.png
  docs/images/Wanchunwei.png
  docs/images/zeyang-li.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/model/task/Name.java
Labels: priority.high, type.task

#48 [build.gradle]: Modified to project's need.
  build.gradle
Labels: priority.high, type.task

#50 [build.gradle]: Removed 'site-seedu'.
  build.gradle
Labels: bug, priority.high, type.task

#60 DeveloperGuide, UserGuide: Updated
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, type.task

#72 UserGuide.adoc: Updated user guide.
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.high, status.close, type.task

#74 update feature: smart suggestion
  docs/team/Zeyang-Li.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/TaskBookParser.java
  src/main/java/seedu/address/logic/suggestions/InputCommandSuggestion.java
  src/main/java/seedu/address/logic/suggestions/StringSimilarity.java
  src/main/java/seedu/address/logic/suggestions/Suggestion.java
  src/main/java/seedu/address/logic/suggestions/Trie.java
  src/main/java/seedu/address/logic/suggestions/WrongCommandSuggestion.java
Labels: priority.high, type.task
